apiVersion: v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  labels:   # these labels are deployment labels
    app: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      name: catalogue
      labels:
        app: catalogue
        project: roboshop
        tier: app
    spec:
       containers:
       - name:
         image: {{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}
         imagePullPolicy: Always
         envFrom:
        - configMapRef:
           name: catalogue
        

   